name: cycad
description: "A playing card deck editor app."
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  file_picker: ^10.3.7
  flex_color_picker: ^3.8.0
  flutter:
    sdk: flutter

  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  archive: ^4.0.7
  share_plus: ^11.0.0
  supabase_flutter: ^2.12.0
  logger: ^2.6.2
  collection: ^1.19.1
  google_fonts: ^6.3.3
  uuid: ^4.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^3.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5



flutter:
  uses-material-design: true